// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVTF0QwfuUpBgPSHwjOHEiIbxowRuCcUw',
    appId: '1:487258896141:web:95d3062c31b17f2b582244',
    messagingSenderId: '487258896141',
    projectId: 'app-on-web-d9829',
    authDomain: 'app-on-web-d9829.firebaseapp.com',
    storageBucket: 'app-on-web-d9829.firebasestorage.app',
    measurementId: 'G-RV2TNNWMGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa54GJFTUPueBtgeN1EhPx3QVONaF1xlQ',
    appId: '1:487258896141:android:01a4bd125df5cbd0582244',
    messagingSenderId: '487258896141',
    projectId: 'app-on-web-d9829',
    storageBucket: 'app-on-web-d9829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFfA5L2HYLisw8NhIb7TsUXNzzQm1ofY',
    appId: '1:487258896141:ios:163ccf4b70322765582244',
    messagingSenderId: '487258896141',
    projectId: 'app-on-web-d9829',
    storageBucket: 'app-on-web-d9829.firebasestorage.app',
    iosBundleId: 'com.example.appOnWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdFfA5L2HYLisw8NhIb7TsUXNzzQm1ofY',
    appId: '1:487258896141:ios:163ccf4b70322765582244',
    messagingSenderId: '487258896141',
    projectId: 'app-on-web-d9829',
    storageBucket: 'app-on-web-d9829.firebasestorage.app',
    iosBundleId: 'com.example.appOnWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVTF0QwfuUpBgPSHwjOHEiIbxowRuCcUw',
    appId: '1:487258896141:web:1e845d4deed22f4d582244',
    messagingSenderId: '487258896141',
    projectId: 'app-on-web-d9829',
    authDomain: 'app-on-web-d9829.firebaseapp.com',
    storageBucket: 'app-on-web-d9829.firebasestorage.app',
    measurementId: 'G-T6PFSFM2JG',
  );
}
